on:
  push:
    branches:
      - master
jobs:
  artifact-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
      - name: Setup dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -qqy build-essential software-properties-common pkg-config wget libpcsclite-dev
      - name: Build
        run: |
          make -j4 build-darwin-amd64 build-linux-amd64 build-darwin-arm64 build-linux-arm64
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build"
      #     tag: "latest"
      #     token: ${{ secrets.GITHUB_TOKEN }}

  # release-test:
  #   runs-on: ubuntu-latest
  #   needs: [artifact-build]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Download macos
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: awsu-macos-latest-amd64
  #         path: build
  #     - name: Download linux
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: awsu-ubuntu-latest-amd64
  #         path: build
  #     - name: Correct goreleaser prebuilt path
  #       run: |
  #         # as it is the format goreleaser expects. See .goreleaser.yml -> prebuilt -> path
  #         mv build/awsu-ubuntu-latest-amd64 build/awsu_linux_amd64
  #         mv build/awsu-macos-latest-amd64 build/awsu_darwin_amd64
  #         ls -lash build
  #     - name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v4
  #       with:
  #         distribution: goreleaser-pro
  #         version: latest
  #         args: release --rm-dist
  #       env:
  #         # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         # GORELEASER_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
